import { styleTags, tags } from "@lezer/highlight"

export const dartHighlight = styleTags({
  "import export library part of as show hide": tags.moduleKeyword,
  "class mixin enum extension typedef": tags.definitionKeyword,
  "var final const": tags.definitionKeyword,
  "extends implements with on": tags.keyword,
  "abstract base interface sealed static late external factory covariant": tags.keyword,
  "get set": tags.keyword,
  "if else while for do switch case default break continue in when": tags.controlKeyword,
  "return assert": tags.controlKeyword,
  "try catch finally throw rethrow": tags.controlKeyword,
  "async async* await sync* yield yield*": tags.controlKeyword,
  "true false": tags.bool,
  "null": tags.null,
  "this super": tags.keyword,
  "void": tags.keyword,
  "Function": tags.typeName,
  "is as": tags.operatorKeyword,
  Identifier: tags.variableName,
  "ClassDeclaration/Identifier": tags.definition(tags.className),
  "MixinDeclaration/Identifier": tags.definition(tags.className),
  "ExtensionDeclaration/Identifier": tags.definition(tags.className),
  "ExtensionTypeDeclaration/Identifier": tags.definition(tags.className),
  "EnumDeclaration/Identifier": tags.definition(tags.className),
  "Typedef/Identifier": tags.definition(tags.typeName),
  "ConstructorDeclaration/Identifier": tags.function(tags.variableName),
  "FunctionDeclaration/Identifier": tags.function(tags.variableName),
  "MemberExpression/Identifier": tags.propertyName,
  "CallExpression/Identifier": tags.function(tags.variableName),
  "TypeIdentifier/Identifier": tags.typeName,
  "Metadata/Identifier": tags.meta,
  Metadata: tags.meta,
  NumberLiteral: tags.number,
  "SingleString DoubleString TripleSingleString TripleDoubleString RawString": tags.string,
  "SingleEscape DoubleEscape TripleSingleEscape TripleDoubleEscape": tags.escape,
  "SingleInterpolationStart DoubleInterpolationStart TripleSingleInterpolationStart TripleDoubleInterpolationStart": tags.special(tags.variableName),
  LineComment: tags.lineComment,
  BlockComment: tags.blockComment,
  "DocComment DocBlockComment": tags.docComment,
  ArithOp: tags.arithmeticOperator,
  LogicOp: tags.logicOperator,
  BitwiseOp: tags.bitwiseOperator,
  ShiftOp: tags.bitwiseOperator,
  CompoundAssign: tags.arithmeticOperator,
  CompareOp: tags.logicOperator,
  LessThan: tags.logicOperator,
  GreaterThan: tags.logicOperator,
  "( )": tags.paren,
  "{ }": tags.brace,
  "[ ] QuestionBracket": tags.squareBracket,
  ";": tags.separator,
  ",": tags.separator,
  ".": tags.derefOperator,
  "=": tags.definitionOperator,
  "=>": tags.operator,
  "@": tags.meta,
})
